/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SaveDialog.java
 *
 * Created on Jan 12, 2012, 3:04:46 PM
 */
package drabed;

import java.util.*;
import java.awt.event.*;
import javax.swing.*;

import java.io.File;

/**
 *
 * @author Stas
 */
interface SaveDialogListener {
    public void onSave(File file);
}

public class SaveDialog extends javax.swing.JFrame {
    private SaveDialogListener mListener;
    
    /** Creates new form SaveDialog */
    public SaveDialog()
    {
        initComponents();
    }
    
    void setListener(SaveDialogListener listener)
    {
        mListener = listener;
    }
    
    JFileChooser getFileChooser()
    {
        return jFileChooser;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Save As...");
        setResizable(false);

        jFileChooser.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        jFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
private void jFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooserActionPerformed
// TODO add your handling code here:
    if(evt.getActionCommand().equals("ApproveSelection"))
    {
        File file = jFileChooser.getSelectedFile();
        
        if(file.exists())
        {
            int n = JOptionPane.showConfirmDialog(this, "Overwrite '" + file.getName() + "'?", "Overwrite?", JOptionPane.YES_NO_OPTION);

            if(n == JOptionPane.NO_OPTION)
                return;
        }
        
        if(mListener != null)
            mListener.onSave(file);
    }
    
    dispose();
}//GEN-LAST:event_jFileChooserActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser;
    // End of variables declaration//GEN-END:variables
}
