.PHONY: clean All

All:
	@echo "----------Building project:[ AnimCom - Release ]----------"
	@cd "AnimCom" && $(MAKE) -f  "AnimCom.mk"
clean:
	@echo "----------Cleaning project:[ AnimCom - Release ]----------"
	@cd "AnimCom" && $(MAKE) -f  "AnimCom.mk" clean
